name: ci_sqs_security
on:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
     
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrehow i sts.DOCKERHUB_TOKEN }}
     
      - name: build image
        run: ./build_image.sh
