name: ci_sqs_security
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
     
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
     
      - name: build image
        run: ./build_image.sh
