name: Daily Docker Job

on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
     
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
     
      - name: Run SQS Security Container
        run: |
          docker run \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e LOG_MODE="${{ secrets.LOG_MODE }}" \
            -e S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}" \
            aviv012/sqs_security:latest
